include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unnecessary_library_name: ignore
    annotate_overrides: warning

linter:
  rules:
    # Disable some strict rules for packages
    always_declare_return_types: false
    always_require_non_null_named_parameters: false